---
resources:
- name: gp-common-go-libs
  type: git
  source:
    uri: https://github.com/greenplum-db/gp-common-go-libs
    branch: ((branch))

jobs:
- name: unit-tests
  plan:
  - in_parallel:
    - get: gp-common-go-libs
      trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
          tag: ((golang-version))-buster
      inputs:
      - name: gp-common-go-libs
        path: go/src/github.com/greenplum-db/gp-common-go-libs
      run:
        path: bash
        args:
        - -c
        - |
          set -ex
          export GOPATH=$PWD/go
          export PATH=$GOPATH/bin:$PATH
          cd $GOPATH/src/github.com/greenplum-db/gp-common-go-libs
          make depend unit
